version: "3.9"
services:
  database:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_MINIALERT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_MINIALERT_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      # - mongo-data:/data/db # (Optional) Use this if you want the data to persist between runs
      - /data/db

  minialert:
    build:
      dockerfile: Dockerfile

    environment:

      # Logging
      MINIALERT_LOG_LEVEL: debug

      # Discord
      MINIALERT_BOT_TOKEN: ${MINIALERT_BOT_TOKEN}
      MINIALERT_BOT_CLIENTID: ${MINIALERT_BOT_CLIENTID}
      MINIALERT_BOT_PERMISSIONS: ${MINIALERT_BOT_PERMISSIONS}

      # Database
      MINIALERT_DATABASE_URI: ${MINIALERT_DATABASE_URI}
      MINIALERT_DATABASE_NAME: ${MINIALERT_DATABASE_NAME}

    volumes:
      - ../configs/minialert.yaml:/minialert.yaml

    depends_on:
      - database

#volumes:
#  mongo-data: