database:

  # The MongoDB URI.
  uri:

  # The name of the database to use.
  database: "minialert"

bot:

  # The bot token.
  token:

  # The client ID.
  clientId:

  # The permissions integer represented as a string.
  # Discord provides resources to help determine the permissions number:
  # https://discord.com/developers/docs/topics/community-resources#permission-calculators
  permissions:

  # (Optional) The list of scopes which the bot requires.
  # Defaults to "bot", "application.commands".
  scopes:
    - bot
    - applications.commands

log:

  # (Optional) The level of logging.
  # Defaults to "info"
  level: info
